better_dashboard_roles:
  groups:
    garten:
      users:
        - schwiegervater
        - schwiegermutter
    admins:
      users:
        - daniel

  dashboards:
    lovelace-garten:
      groups:
        - garten
        - admins
    lovelace-wohnung:
      groups:
        - admins
        - wohnung

  default_dashboard:
    garten: lovelace-garten
    admins: lovelace-wohnung
    wohnung: lovelace-wohnung

  options:
    hide_sidebar_items: true
    redirect_blocked_dashboards: true
    hide_admin_menu_for_non_admin: true
    debug: false
